### ISSUE TITLE
Feature request MathNodeExpression.isValidString(String expression)

### ISSUE THREAD

**Issue by VittorioParagallo** [Sominemo/Math-Parser-Dart#4]
introduce a check like MathNodeExpression.isValidString(String expression) to check if the expression is valid before calling MathNodeExpression.fromString to avoid launching exceptions.

**Comment by Sominemo** [comment]
Hi!

Ideally `.fromString()` is _the_ validator function, because I can't tell for sure if a string is valid without parsing it — implementing such a method would mean the string would get parsed twice in a lot of cases.

If it works for you, I could implement a validate function which would return a result object like this:
`{isValid: bool, expression: MathNode?, error: MathException?}`

**Comment by VittorioParagallo** [comment]
It would be nice.. but if the returned object has a MathException It means
that under the hoods an exception Will be thrown anyways. Usually i try to
avoid as much as i can exceptions if are not real. I mean logically i can
understand the exception on "calc" with a wrong exception, but in
fromString for example if i want to check user input while he Is typing i
ll end up having a lot of exceptions

Il lun 12 ago 2024, 06:53 Sominemo ***@***.***> ha scritto:

**Comment by Sominemo** [comment]
The way the parser works is that it will throw an exception whenever during parsing it meets a condition that makes further parsing nonviable, and will stop any further processing.

Errors are structured and described in [the docs](https://pub.dev/documentation/math_parser/latest/math_parser/math_parser-library.html) under Exceptions to provide users with feedback on what exactly is wrong with the expression.

I suggest to `try {..} on MathException catch (e) {}`, treating caught MathException's as invalid user input and using the typed exception info to provide feedback to the user.

Making a simple method which parses a string but returns a single bool value whenever there's an exception caught might make debugging harder if there's some exception not directly related to parsing thrown in my code, and pushes library consumers to use a non-optimal solution which hides complexity but makes program parse the string twice in a lot of use cases.
